services:
    mvn-web-app:
         image: 590183929966.dkr.ecr.ap-south-1.amazonaws.com/maven-web-application:VERSION
         ports:
         - 8081:8080
         networks:
         - mvnappnet
         healthcheck:
           test: ["CMD", "curl", "-f", "http://localhost:8080"]
           interval: 1m30s
           timeout: 10s
           retries: 3
           start_period: 40s
           start_interval: 5s
networks:
    mvnappnet:
        driver: bridge
