name: mwa

services:
   mavenwebapp:
      image: 590183929966.dkr.ecr.ap-south-1.amazonaws.com/REPO:VERSION
      ports:
      - 8080:8080
      networks:
      - springappbridge
networks:
   springappbridge:
        driver: bridge
